Repository randombar164/ouchi_bar, pull requests merged in 2022-06, with the labels that each got.

#92 WIP Fix/#66 improve accuracy
  frontend/package.json
  frontend/src/pages/scan/MultiResults.tsx
  frontend/src/pages/scan/NoResult.tsx
  frontend/src/pages/scan/Scanner.tsx
  frontend/src/pages/scan/SingleResult.tsx
  frontend/src/pages/scan/index.page.tsx
  frontend/src/utils/contexts/provider.tsx
  frontend/src/utils/types/type.ts
  frontend/yarn.lock
Labels: wip

#96 IngredientCardの修正
  frontend/src/components/IngredientCard.tsx
  frontend/src/pages/register/index.page.tsx
Labels: bug

#99 topページのfooterを削除
  frontend/src/components/Layout/nonFooter.tsx
  frontend/src/pages/blog/index.page.tsx
Labels: bug

#120 酒蔵ページをMUIに移行
  docker-compose.yml
  frontend/next.config.js
  frontend/src/components/Layout/index.tsx
  frontend/src/pages/blog/index.page.tsx
  frontend/src/pages/sakagura/SingleShelf.tsx
  frontend/src/pages/sakagura/index.page.tsx
  frontend/src/styles/SingleShelf.module.css
  frontend/yarn.lock
Labels: レビューお願いします！
